##############################
# General level requirements #
##############################

# Pull official base image from DockerHub
FROM gitea/gitea:1.21.7-rootless@sha256:5d433ef2ebae7eae7b0d0ec42263645a9d200d342fc31ea5bca9745611f89811
